import dns from "node:dns";
dns.setServers["8.8.8.8" , "8.8.4.4"]

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Foother from "@/components/shared/Foother";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="dark"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <body className="min-h-full">
        <Navbar></Navbar>
        <main className="  bg-slate-900 px-10 sm:px-3">
          {children}
        </main>
        <Foother></Foother>
      </body>
    </html>
  );
}
